[build-system]
requires = ["setuptools>=61", "wheel", "numpy", "cython"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/_version.py"
version_scheme = "guess-next-dev"
local_scheme = "node-and-date"